name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spotify-gender-tracker:latest

  deploy_to_koyeb:
    name: Deploy to Koyeb
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Koyeb Deployment
        run: |
          curl -X POST "https://app.koyeb.com/v1/apps/${{ secrets.KOYEB_SERVICE_ID }}/services/deploy" \
          -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "spec": {
              "definition": {
                "image": "'"${{ secrets.DOCKER_USERNAME }}/spotify-gender-tracker:latest"'"
              }
            }
          }'
